config/routes.rb
Rakuchan::Application.routes.draw do

  resources :topics do
    resources :comments
  end

  root :to => 'topics#index'

end

app/models/comment.rb
# coding: utf-8

class Comment
  include Mongoid::Document
  field :name, :default => '名無しさん'
  field :posted_at, :type => DateTime, :default => DateTime.now
  field :content
  embedded_in :topic, :inverse_of => :comments

  validates_presence_of :name, :posted_at, :content
  validates_length_of   :name, :minimum => 4, :maximum => 100
  validates_length_of   :content, :minimum => 4, :maximum => 500
end

app/models/topic.rb
class Topic
  include Mongoid::Document
  field :title
  embeds_many :comments

  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
# coding: utf-8

class CommentsController < ApplicationController
  def index
    @topic = Topic.find(params[:topic_id])
    @comment = Comment.new
  end

  def create
    @topic   = Topic.find(params[:topic_id])
    params[:comment][:name] = '名無しさん' if  params[:comment][:name] == ""
    @comment = Comment.new(params[:comment])
    @topic.comments << @comment
    @topic.save
    redirect_to topic_comments_url(@topic) 
  end
end

app/controllers/topics_controller.rb
# coding: utf-8

class TopicsController < ApplicationController
  def index
    @topics = Topic.all.to_a
    @comment = Comment.new
  end

  def new
    @topic   = Topic.new
    @comment = Comment.new
  end

  def create
    @topic = Topic.new(params[:topic])
    params[:topic][:comment][:name] = '名無しさん' if  params[:topic][:comment][:name] == ""
    @topic.comments << Comment.new(params[:topic][:comment])
    @topic.save
    redirect_to topics_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
# encoding: utf-8

module TopicsHelper

  def insert_slash(topics, topic)
    if topics.first != topic && topics.last != topic
      " ／ "
    end
  end
end

app/views/comments/index.html.erb
<div class="item">
    <div class="titleArea"><h3><%= @topic.title %></h3></div>
    <% @topic.comments.each_with_index do |comment,i| %>
      <div class="infoArea">
        <%= i+1 %>
        名前：<%= comment.name %>
        <%= comment.posted_at.strftime("%Y年 %m月 %d日, %H:%M:%S") %>
      </div>
      <div class="contentArea">
        <%= comment.content %>
      </div>
    <% end %>
    <%= form_for @comment, :url => {:controller => :comments, :action => :create, :topic_id => @topic.id}  do |f| %>
      <div class="clearfix">
        <div class="nameArea">
          <label>名前</label>
          <%= f.text_field :name, :value => nil %>
        </div>
        <div class="submitArea">
          <%= f.submit "書き込む" , :class => "btn-primary" %>
        </div>
      </div>
          

      <%= f.text_area :content, :size => "4" %>

    <% end %>
  </div>

app/views/comments/new.html.erb
<%= form_for @comment, :url => topic_comments_path, :id => params[:topic_id] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit "create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rakuchan" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Rakuchan</a>
          <div class="container nav-collapse">
            <!-- <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul> -->
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div id="<%= controller.controller_name %>" class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>リンク集</h3>
                <ul class="nav nav-list">
                  <li><%= link_to "", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/index.html.erb
<% topics = @topics.reverse %>
<div class="topicArea clearfix">
<%= button_to "トピック作成", new_topic_path, :method => :get, :class => 'btn-primary' %>
<div class="hero-unit">
  <% topics.each do |topic| %>
    <%= link_to topic.title, topic_comments_path(topic)  %> 
    <%= insert_slash(@topics, topic) %>
  <% end %>
</div>

<% topics.each do |topic| %>
  <div class="item">
    <div class="titleArea"><h3><%= link_to topic.title, topic_comments_path(topic.id) %></h3></div>
    <% topic.comments.each_with_index do |comment,i| %>
      <div class="infoArea">
        <%= i+1 %>
        名前：<%= comment.name %>
        <%= comment.posted_at.strftime("%Y年 %m月 %d日, %H:%M:%S") %>
      </div>
      <div class="contentArea">
        <%= comment.content %>
      </div>
    <% end %>
    <%= form_for @comment, :url => {:controller => :comments, :action => :create, :topic_id => topic.id}  do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, :value => nil %>

      <%= f.label :content %>
      <%= f.text_area :content, :size => "4" %>

      <%= f.submit "create" %>
    <% end %>
  </div>
<% end %>
</div>

app/views/topics/new.html.erb
<%= form_for @topic do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.fields_for @comment do |f2| %>
      <%= f2.label :name %>
      <%= f2.text_field :name, :value => nil %>

      <%= f2.label :content %>
      <%= f2.text_area :content, :size => "4" %>
  <% end %>

  <%= f.submit "create" %>

<% end %>